import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MyComponent from '../components/Test'
import { Card, Container, Grid, Row, Spacer, Text, Image, Divider, Button, Input, Avatar } from '@nextui-org/react'
import protectedRoute from '../hocs/protectedRouter'
import { IoMdHeartEmpty, IoMdHeart, IoMdChatboxes } from "react-icons/io";

const testData = [
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
  },
  {
    "userId": 1,
    "id": 2,
    "title": "qui est esse",
    "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
  },
  {
    "userId": 1,
    "id": 3,
    "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
  }
]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spacer y={4} />
      <Container fluid xs>
        {testData.map(({ userId, title, body }) => (
          <>
            <Row key={userId}>
              <Card>
                <Card.Header>
                  <Grid.Container>
                    <Grid>
                      <Text h3>{title}</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Divider />
                <Card.Body>
                  <Text>{body}</Text>
                  <Spacer y={1} />
                  <Image
                    width="100%"
                    height="100%"
                    src={"/images/default_avt.jpg"}
                  />
                  <Row align="center">
                    <IoMdHeart size={20} color="red" />
                    <Spacer x={0.3} />
                    <Text>You and 100 others</Text>
                  </Row>
                </Card.Body>
                <Divider />
                <Card.Footer css={{ flexDirection: "column" }}>
                  <Row gap={10} justify="space-around" align="center">
                    <Button light>
                      <IoMdHeartEmpty size={30} />
                    </Button>
                    <Button light>
                      <IoMdChatboxes size={30} />
                    </Button>
                  </Row>
                  <Divider />
                  <Spacer y={1} />
                  <Grid.Container gap={2}>
                    <Grid xs={1}>
                      <Avatar
                        bordered
                        color="primary"
                        src="/images/default_avt.jpg"
                      />
                    </Grid>
                    <Grid xs={11}>
                      <Input
                        width="100%"
                        bordered
                        borderWeight="normal"
                        color="primary"
                        aria-labelledby="comment"
                        placeholder="Comment anything"
                      />
                    </Grid>
                  </Grid.Container>
                </Card.Footer>
              </Card>
            </Row>
            <Spacer y={2} />
          </>
        ))}
      </Container>
    </div>
  );
}

export default protectedRoute(Home);
